name: "Send OneSignal Notification"
description: "Receive OneSignal push notification on your devices using Github Actions"
author: "Jasdeep Singh"
# branding:
#   icon: 'send'
#   color: 'red'
runs:
  using: "docker"
  image: "Dockerfile"
