name: "One Signal Github Action"
description: "Github Action for OneSignal Notification Receive push notification from OneSignal to your devices using Github Actions"
inputs:
  apiKey: # id of input
    description: "OneSignal API Key"
    required: true
  appId: # id of input
    description: "OneSignal App Id"
    required: true
  contentsEn: # id of input
    description: 'Notification "contents" in En locale, https://documentation.onesignal.com/reference/create-notification'
    required: false
    default: "No message specified"
  headingsEn: # id of input
    description: 'Notification "headings" in En locale, https://documentation.onesignal.com/reference/create-notification'
    required: false
  isAndroid: # id of input
    description: "https://documentation.onesignal.com/reference/create-notification"
    required: false
  isIos: # id of input
    description: "https://documentation.onesignal.com/reference/create-notification"
    required: false
  isAnyWeb: # id of input
    description: "https://documentation.onesignal.com/reference/create-notification"
    required: false
  webUrl: # id of input
    description: "https://documentation.onesignal.com/reference/create-notification"
    required: false

runs:
  using: "node16"
  main: "index.js"
